export const queryKeys = {
  auth: {
    me: ["auth", "me"] as const,
    session: ["auth", "session"] as const
  },
  health: ["health"] as const,
  publicPlans: ["public", "subscriptions", "plans"] as const,
  publicCharities: ["public", "charities", "list"] as const,
  publicCharityDetail: (id: string) => ["public", "charities", "detail", id] as const,
  plans: ["subscriptions", "plans"] as const,
  subscriptionConfig: ["subscriptions", "config"] as const,
  mySubscriptions: ["subscriptions", "mine"] as const,
  myPayments: ["payments", "mine"] as const,
  charities: ["charities", "list"] as const,
  charityDetail: (id: string) => ["charities", "detail", id] as const,
  myCharitySelection: ["charities", "selection"] as const,
  myDonations: ["charities", "donations"] as const,
  profileStatus: ["users", "profile-status"] as const,
  myProfile: ["users", "me"] as const,
  myScores: ["scores", "mine"] as const,
  myQualifyingScores: ["scores", "qualifying"] as const,
  scoreEligibility: ["scores", "eligibility"] as const,
  draws: ["draws", "list"] as const,
  drawConfig: ["draws", "config"] as const,
  drawDetail: (id: string) => ["draws", "detail", id] as const,
  drawEntries: (id: string) => ["draws", "entries", id] as const,
  drawPrizePool: (id: string) => ["draws", "prize-pool", id] as const,
  drawResult: (id: string) => ["draws", "result", id] as const,
  notifications: ["notifications", "mine"] as const,
  winners: ["winners", "mine"] as const,
  winnerDetail: (id: string) => ["winners", "detail", id] as const,
  winnerProofs: (id: string) => ["winners", "proofs", id] as const,
  adminOverview: ["reports", "overview"] as const
};
